<?php 

    function owner_list($attr){

        $attr = shortcode_atts( array(
            'function_page_no' => '509',
        ), $attr, 'owner-list' );

        $html    = "";

        $html   .= '<script>';
        $html   .= '    $(document).ready(function () {';
        $html   .= '    var a = {';
        $html   .= '        home: "homeSearch occupancy calendar monthPicker freetextSuggest freetextHint cardFees promotions".split(" "),';
        $html   .= '        results: "advancedSearch calendar monthPicker occupancy dateFilters freetextSuggest tooltip tooltip_analytics mediaQuery map mapResults currencyConverter fixedDateBar shortlist adslot".split(" "),';
        $html   .= '        details: "reviews calendar monthPicker dateFilters tooltip mediaQuery map mapDetails galleryNav gallery shortlist detailsText currencyConverter detailsBedding".split(" "),';
        $html   .= '        seo: "advancedSearch calendar monthPicker dateFilters tooltip mediaQuery map mapResults shortlist currencyConverter adslot dealsIframe".split(" "),';
        $html   .= '        seopoi: ["mediaQuery", "hotelsTabs", "map", "mapResults", "mobile"],';
        $html   .= '        seomap: ["mediaQuery", "hotelsTabs", "map", "mapResults", "mobile"],';
        $html   .= '        seomobile: ["mediaQuery", "hotelsTabs", "mobile"],';
        $html   .= '        hotelsenquiry: ["enquiry"],';
        $html   .= '        hotelsregion: ["mediaQuery", "mobile", "hotelsTabs", "dealsIframe", "currencyConverter"],';
        $html   .= '        hotelsdetails: "hotelsTabs calendar monthPicker dateFilters tooltip map mapDetails gallery galleryNav shortlist currencyConverter reviews detailsText".split(" ")';
        $html   .= '    };';
        $html   .= '    "undefined" !== typeof wotifConfig && a[wotifConfig.page] && wotif.utils.initModules(wotif, a[wotifConfig.page])';
        $html   .= '});';
        $html   .= '$(function(a) {';
        $html   .= '    var syndicate_cmm_date = $("#syndicate_cmm_date").val();';
        $html   .= '    var minimumDate = new Date();';
        $html   .= '    if(typeof syndicate_cmm_date != "undefined")';
        $html   .= '    {';
        $html   .= '        minimumDate = new Date(syndicate_cmm_date);    ';    
        $html   .= '    }';
            //alert(minimumDate);
        $html   .= '    generateDate(minimumDate);';
        $html   .= '});';
        $html   .= 'function generateDate(minimumDate)';
        $html   .= '{';
        $html   .= '$( "#date_owner" ).datepicker({';

                //dayNamesMin: f.date.daysOfWeek.shortDays,
        $html   .= '        buttonText: "",';
        $html   .= '        duration: 0,';
        $html   .= '        firstDay: 1,';
        $html   .= '        dateFormat: "D dd M yy",';
        $html   .= '        altFormat: "D dd M yy",';
        $html   .= '        altField: "input[name=\'date_owner\']",';
        $html   .= '        minDate: minimumDate,';
                
        $html   .= '        buttonImageOnly: !0,';
        $html   .= '        showOn: "both",';
        $html   .= '        showOtherMonths: !0,';
        $html   .= '        showMonthPicker: !0,';
        $html   .= '        changeMonth: true,';
               // changeYear: true,
        $html   .= '        constrainInput: !1';
        $html   .= '});';
        $html   .= '}';
        $html   .= '</script>';

        $html   .= '<div id="primary">';
        $html   .= '    <div id="content" role="main">';
        $html   .= '        <div class="wrap create-edit-cprof bcknd">';
        $html   .= '            <h1>CREATE/ EDIT CUSTOMER PROFILE</h1>';
        $html   .= '            <h2>EXISTING CUSTOMER AND SYNDICATE DETAILS</h2>';
        $html   .= '            <form name="owner_form" id="owner_form" method="post" action="#" enctype="multipart/form-data">';  
                                
        $html   .= '            <div class="top">';
        $html   .= '                <div><label>Syndicate :</label> <select name="syndicate_list" id="syndicate_list" onchange="getSurnames(this)">';
                                        global $wpdb;
                                        $sql1 = "SELECT syndicate, cmm_date FROM wp_syndicate_details where status = 1";
                                        $results_total = $wpdb->get_results($sql1);
                                        $cmm_date = '';
                                        foreach ($results_total as $key) { if($cmm_date == '') $cmm_date = $key->cmm_date;
                                            $html   .= '<option value="'.$key->syndicate.'" >'.$key->syndicate.'</option>';
                                        }
        $html   .= '                </select>';
        $html   .= '            </div>';
        $html   .= '                <div><label>First Name:</label>';
        $html   .= '                    <select name="select-first-name" id="select-first-name">';
                                 
            //                            $sql1 = "SELECT first_name FROM wp_owner_details ";
            //                            $results_total = $wpdb->get_results($sql1);
            //                            foreach ($results_total as $key) {
                                   
        $html   .= '                        <option value=""></option>';
        $html   .= '                    </select>';
        $html   .= '                <label style="margin:0 0 0 10px;">Surname:</label>';
        $html   .= '                    <select name="select-surname" id="select-surname" onchange="getOwnersData(this)">';
                                
            //                            $sql1 = "SELECT surname FROM wp_owner_details";
            //                            $results_total = $wpdb->get_results($sql1);
            //                            foreach ($results_total as $key) { 
                                    
        $html   .= '                         <option value=""></option>';
        $html   .= '                    </select>';
        $html   .= '                </div>';
        $html   .= '            </div>';
        $html   .= '            <div>';
        $html   .= '                <a href="javascript:void(0)" id="add" onclick="addAction()">add</a>';
        $html   .= '                <a href="javascript:void(0)" id="edit" onclick="editAction()">edit</a>';
        $html   .= '                <a href="javascript:void(0)" onclick="deleteRow()">delete</a>';
        $html   .= '                <a style="margin-right:0;" href="javascript:void(0)" id="save">save</a></div>';
        $html   .= '            <div class="left">';
        $html   .= '                <h2>PERSONAL INFORMATION</h2>';
        $html   .= '                <div class="pi-top">';
        $html   .= '                    <span><label>*First Name:</label><input type="text" name="first_name" id="first_name" class="validate[required] text-input" value="" /></span>';
        $html   .= '                    <span><label>*Surname:</label><input type="text" name="surname" id="surname" class="validate[required] text-input" value="" /></span>';
        $html   .= '                    <span><label style="margin-top:16px;">Address:</label><textarea name="address" id="address"></textarea></span>';
        $html   .= '                </div>';
        $html   .= '                <div class="pi-mdl">';
        $html   .= '                    <span><label style="width:45px;">City:</label><input type="text" name="city" class="validate[required] text-input" id="city" value="" />';
        $html   .= '                    <label style="margin:0 0 0 18px;">Postcode:</label><input type="text" name="pincode" id="pincode" class="validate[required] text-input" value="" /></span>';
        $html   .= '                    <span><label style="width:45px;">State:</label><input type="text" name="state" id="state" class="validate[required] text-input" value="" />';
        $html   .= '                    <label style="margin:0 0 0 18px;">Country:</label><input type="text" name="country" id="country" class="validate[required] text-input" value="" /></span>';
        $html   .= '                    <span><label style="width:45px;">DOB:</label><input type="text" name="dob" id="dob" class="validate[required] text-input" value="" />';
        $html   .= '                    <label style="margin:0 0 0 18px;">Sex:</label><input type="text" name="sex" id="sex" class="validate[required] text-input" value="" /></span>';
        $html   .= '                    <span><label style="width:45px;">Tel:</label><input type="text" name="tel" id="tel" class="validate[required] text-input" value="" />';
        $html   .= '                    <label style="margin:0 0 0 18px;">Mobile:</label><input type="text" name="mobile" class="validate[required] text-input" id="mobile" value="" /></span>';
        $html   .= '                </div>';
        $html   .= '                <label>*Email:</label><input class="email validate[required]" type="text" name="email" id="email"value="" />';
        $html   .= '                <div class="e-contect-no" style="width:50%;"><label>*Password:</label>';
        $html   .= '                    <input type="text" name="password" id="password" value="" />';
        $html   .= '                </div>';
        $html   .= '                <div class="e-contect-no" style="width:50%;"><label>Emergency Contact name/ no:</label>';
        $html   .= '                    <input type="text" name="contact_no" id="contact_no" value="" />';
        $html   .= '                </div>';
        $html   .= '                <div class="color-picker">';
        $html   .= '                    <label>*Color:</label>';
        $html   .= '                    <span><div style="background:yellow;"></div><input type="radio" value="yellow" class="validate[required] radio" id="yellow" name="color"/></span>';
        $html   .= '                    <span><div style="background:pink;"></div><input type="radio" value="pink" class="validate[required] radio" id="pink" name="color"/></span>';
        $html   .= '                    <span><div style="background:purple;"></div><input type="radio" value="purple" class="validate[required] radio" id="purple" name="color"/></span>';
        $html   .= '                    <span><div style="background:magenta;"></div><input type="radio" value="magenta" class="validate[required] radio" id="magenta" name="color"/></span>';
        $html   .= '                    <span><div style="background:cyan;"></div><input type="radio" value="cyan" class="validate[required] radio" id="cyan" name="color"/></span>';
        $html   .= '                    <span><div style="background:green;"></div><input type="radio" value="green" class="validate[required] radio" id="green" name="color"/></span>';
        $html   .= '                    <span><div style="background:orange;"></div><input type="radio" value="orange" class="validate[required] radio" id="orange" name="color"/></span>';
        $html   .= '                    <span><div style="background:blue;"></div><input type="radio" value="blue" class="validate[required] radio" id="blue" name="color"/></span>';
        $html   .= '                    <div id="color-error" style="display: none; color: red">This is required</div>';
        $html   .= '                </div>';
        $html   .= '                <div class="syndiate-iftn">';
        $html   .= '                    <h2>SYNDICATE INFORMATION</h2>';
        $html   .= '                    <span><label>Boat License No:</label><input type="text" name="boat_no" id="boat_no" class="validate[required] text-input" value="" /></span>';
        $html   .= '                    <span><label>Syndicate / Boat:</label>';
        $html   .= '                    <select name="syndicate" id="syndicate">';
                                     
                                        $sql1 = "SELECT syndicate FROM wp_syndicate_details where status = 1";
                                        $results_total = $wpdb->get_results($sql1);
                                        foreach ($results_total as $key) { 
                                           $html   .= '<option value="'.$key->syndicate.'" >'.$key->syndicate.'</option>';
                                        }
                                         
        $html   .= '                    </select>';
        $html   .= '                   </span>';
        $html   .= '                    <span><label style="width:228px !important;">Date of ownership commencement:</label>';
        $html   .= '                    <input type="text" class="commencement" name="date_owner" id="date_owner" class="validate[required] text-input" value="" /></span>';
        $html   .= '                </div>';
        $html   .= '            </div>';
        $html   .= '            <div class="rgt">';
        $html   .= '                <h2>ACCOUNT DETAILS</h2>';
        $html   .= '                <div class="adetails">';
        $html   .= '                    <span><label>Name of Account:</label><input type="text" name="name_account" id="name_account" class="validate[required] text-input" value="" /></span>';
        $html   .= '                    <span><label>BSB:</label><input type="text" name="bsb" id="bsb" class="validate[required] text-input" value="" /></span>';
        $html   .= '                    <span><label>Account Number:</label><input type="text" name="account_no" id="account_no" class="validate[required] text-input" value="" /></span>';
        $html   .= '                </div>';
        $html   .= '            <div class="cc-details">';
        $html   .= '                <h2>CREDIT CARD DETAILS</h2>';
        $html   .= '                <span><label>Name of Card:</label><input type="text" name="cc_card_name" id="cc_card_name" value="" /></span>';
        $html   .= '                <span><label>Card Number:</label><input type="text" name="cc_card_no" id="cc_card_no" value="" /></span>';
        $html   .= '                <span><label>Expiry Date:</label><input type="text" name="cc_exp_date" id="cc_exp_date" value="" /></span>';
        $html   .= '                <span><label>CCV number:</label><input type="text" name="cc_cvv" id="cc_cvv" value="" /></span>';
        $html   .= '                <span><label style="width:162px;">Visa/ Master Card/ Amex:</label><input class="cc-cards" type="text" name="cc_type" id="cc_type" value="" /></span>';
        $html   .= '            </div>';
        $html   .= '            <div class="nominated-ddetails">';
        $html   .= '                <h2>NOMINATED DRIVER DETAILS</h2>';
        $html   .= '                <span><label>First Name:</label><input type="text" name="nd_first_name" id="nd_first_name" value="" /></span>';
        $html   .= '                <span><label>Surname:</label><input type="text" name="nd_surname" id="nd_surname" value="" /></span>';
        $html   .= '                <span><label>Telephone no:</label><input type="text" name="nd_tel" id="nd_tel" value="" /></span>';
        $html   .= '                <span><label>License no:</label><input type="text" name="nd_license" id="nd_license" value="" /></span>';
        $html   .= '            </div>';
        $html   .= '      </div>';
        $html   .= '      <input type="hidden" name="user_id" id="id" value="" />';
        $html   .= '      <input type="hidden" name="user" id="user_id" value="" />';
        $html   .= '      <input type="hidden" name="status" id="status" value="1" />';
        $html   .= '      <input type="hidden" name="color" id="color" value="" />';
        $html   .= '      <input type="hidden" name="add_button_click" id="add_button_click" value="0" />';
        $html   .= '      <input type="hidden" name="edit_button_click" id="edit_button_click" value="0" />';
        $html   .= '      <input type="hidden" name="syndicate_cmm_date" id ="syndicate_cmm_date" value="'.$cmm_date.'"';

        $html   .= '        </form>  ';
        $html   .= '        </div>';


        $html   .= '    <div id="status_message1"></div>';
        $html   .= '    </div>';
        $html   .= '</div>';
        

        $html   .= '<script type="text/javascript">  ';    
        $html   .= '    jQuery(document).ready( function() {';
        $html   .= '        getSurnames(document.getElementById("syndicate_list"));';
        $html   .= '        makeReadonly()';
        $html   .= '    });';
        $html   .= '   $ = jQuery.noConflict();';
        $html   .= '   var validationArray = new Array();';
        $html   .= '   validationArray[0] = "first_name";';
        $html   .= '   validationArray[1] = "surname";';
        $html   .= '   validationArray[2] = "email";';
        $html   .= '   validationArray[3] = "password";';
           
        $html   .= '   function getSurnames(select)';
        $html   .= '   {';
        $html   .= '       removeAll();';
        $html   .= '       setDefaultValues();';
        $html   .= '       var tempSyndicateDate = "";';
        $html   .= '       data1={};';
        $html   .= '       data1.syndicate = select.value;';
        $html   .= '       data1.type = "ownerListSurname";';
        $html   .= '       $.ajax({';
        $html   .= '            type:"POST",';
        $html   .= '            url : "?page_id='.$attr["function_page_no"].'",';
        $html   .= '            dataType : "text",';
        $html   .= '            data : data1,';
        $html   .= '            success : function(result){';
        $html   .= '                console.log(result);';
        $html   .= '                obj = JSON.parse(result);';
        $html   .= '                var options = "<option value=\'\'>Please Select</option>";';
        $html   .= '                for(i in obj)';
        $html   .= '                {';
        $html   .= '                    for(j in obj[i])';
        $html   .= '                    {';
                                //alert(obj[i][j]);
        $html   .= '                        if(j == "surname")';
        $html   .= '                        options += "<option value=\'"+obj[i][j]+"\'>"+obj[i][j]+"</option>";';                        
        $html   .= '                        if(j == "cmm_date")';
        $html   .= '                        {';
        $html   .= '                            var tempData = obj[i][j];';
        $html   .= '                            $("#syndicate_cmm_date").val(tempData);';
        $html   .= '                            if(tempSyndicateDate == "")';
        $html   .= '                                tempSyndicateDate = tempData;';
        $html   .= '                            console.log("tempSyndicateDate - "+tempSyndicateDate);';
        $html   .= '                        }  ';                          
        $html   .= '                    }';
        $html   .= '                }';
        $html   .= '                $("#select-surname").html(options); ';
        $html   .= '                makeReadonly();';
        $html   .= '                if(tempSyndicateDate != "")';
        $html   .= '                {';
        $html   .= '                    $( "#date_owner" ).datepicker( "option", "minDate", tempSyndicateDate);';
        $html   .= '                }';
        $html   .= '            },';

        $html   .= '        });';
        $html   .= '   }';
           
        $html   .= '   function getOwnersData(select)';
        $html   .= '   {';
        $html   .= '       removeAll();';
        $html   .= '       setDefaultValues();';
        $html   .= '       data2={};';
        $html   .= '       data2.syndicate = $("#syndicate_list").val();';
        $html   .= '       data2.surname = select.value; ';   
        $html   .= '       data2.type = "getOwnerList"; ';      
        $html   .= '       $.ajax({';
        $html   .= '            type:"POST",';
        $html   .= '            url : "?page_id='.$attr["function_page_no"].'",';
        $html   .= '            dataType : "text",';
        $html   .= '            data : data2,';
        $html   .= '            success : function(result){';
        $html   .= '                console.log(result);';
        $html   .= '                obj = JSON.parse(result);';
        $html   .= '                var options = "";';
        $html   .= '                for(i in obj)';
        $html   .= '                {';
        $html   .= '                    for(j in obj[i])';
        $html   .= '                    {';
        $html   .= '                        if(j == "color")';
        $html   .= '                        {';
        $html   .= '                            if(document.getElementById(obj[i][j]))';
        $html   .= '                            {';
        $html   .= '                                document.getElementById(obj[i][j]).checked = "checked";';
        $html   .= '                            }';
        $html   .= '                            if(document.getElementById(j))';
        $html   .= '                                document.getElementById(j).value = obj[i][j];';
        $html   .= '                        }else if(j == "first_name")';
        $html   .= '                        {';
        $html   .= '                            options += "<option value=\'"+obj[i][j]+"\'>"+obj[i][j]+"</option>";';
        $html   .= '                            $("#select-first-name").html(options);';
        $html   .= '                            if(document.getElementById(j))';
        $html   .= '                                document.getElementById(j).value = obj[i][j];';
        $html   .= '                        }else if(document.getElementById(j))';
        $html   .= '                        {';
        $html   .= '                            if(document.getElementById(j))';
        $html   .= '                                document.getElementById(j).value = obj[i][j];';
        $html   .= '                        }';
                                    
        $html   .= '                    }';
        $html   .= '                }';
        $html   .= '                makeReadonly();';
        $html   .= '            },';

        $html   .= '        });';
        $html   .= '   }';
           
        $html   .= '   function getOwnerColors()';
        $html   .= '   {';
        $html   .= '        var syndicateName = $("#syndicate_list").val();';
                //alert(syndicateName);
        $html   .= '        var ownerColor =  {};';
        $html   .= '        ownerColor.type = "getOwnerColors";';
        $html   .= '        ownerColor.syndicateName = syndicateName; ';
        $html   .= '        $.ajax({';
        $html   .= '            type:"POST",';
        $html   .= '            url : "?page_id='.$attr["function_page_no"].'",';
        $html   .= '            dataType : "text",';
        $html   .= '            data : ownerColor,';
        $html   .= '            success : function(result){';
        $html   .= '                if(result != "")';
        $html   .= '                {';
        $html   .= '                    var currentOwnerColor = $("#color").val();';
        $html   .= '                    var colorArray = result.split(",");';
        $html   .= '                    for(i in colorArray)';
        $html   .= '                    {';
        $html   .= '                        var colorId = colorArray[i];';
        $html   .= '                        var addButtonClicked = parseInt($("#add_button_click").val());';
        $html   .= '                        if(!addButtonClicked)';
        $html   .= '                        {';
        $html   .= '                            if(currentOwnerColor != colorId)';
        $html   .= '                            {';
        $html   .= '                                $("#"+colorId).attr("disabled", true);   '; 
        $html   .= '                            }';
        $html   .= '                        }else{';
        $html   .= '                            $("#"+colorId).attr("disabled", true);';
        $html   .= '                        }';
        $html   .= '                    }';
        $html   .= '                }';
        $html   .= '            },';                  
        $html   .= '        });';
        $html   .= '   }';
           
        $html   .= '   function checkInputValues()';
        $html   .= '   {';
        $html   .= '       $("#owner_form").find(":input").each(function(){';
        $html   .= '          $(this).change(function(){';
        $html   .= '              console.log(change);';
        $html   .= '              if( change !== 1 ) change = 1; ';
        $html   .= '          });';
        $html   .= '       }); ';
        $html   .= '   }';
        $html   .= '   (function($){';
        $html   .= '        $("#save").click(function( event ) {';
        $html   .= '            var validateFields = checkInputFields();';
        $html   .= '            if(!validateFields)';
        $html   .= '            {';
        $html   .= '                return false;';
        $html   .= '            }';
        $html   .= '            var edit_button_clicked = $("#edit_button_click").val();';
        $html   .= '            if(edit_button_clicked)';
        $html   .= '            {';
        $html   .= '                var conf = confirm("Would you like to save changes of this customer account?");';
        $html   .= '            }else{';
        $html   .= '                var conf = confirm("Would you like to create this customer account?");';
        $html   .= '            } ';          
        $html   .= '            if(conf == true)';
        $html   .= '            {';
        $html   .= '                data={};';
        $html   .= '                data.first_name = $("[name=\'first_name\']").val();';
        $html   .= '                data.syndicate = $("[name=\'syndicate\']").val();';
        $html   .= '                data.surname = $("[name=\'surname\']").val();';
        $html   .= '                data.address = $("[name=\'address\']").val();';
        $html   .= '                data.city = $("[name=\'city\']").val();';
        $html   .= '                data.state = $("[name=\'state\']").val();';
        $html   .= '                data.pincode = $("[name=\'pincode\']").val();';
        $html   .= '                data.country = $("[name=\'country\']").val();';
        $html   .= '                data.dob = $("[name=\'dob\']").val();';
        $html   .= '                data.sex = $("[name=\'sex\']").val();';
        $html   .= '                data.tel = $("[name=\'tel\']").val();';
        $html   .= '                data.mobile = $("[name=\'mobile\']").val();';
        $html   .= '                data.email = $("[name=\'email\']").val();';
        $html   .= '                data.password = $("[name=\'password\']").val();';
        $html   .= '                data.contact_no = $("[name=\'contact_no\']").val();';
        $html   .= '                data.color = $("[name=\'color\']:checked").attr("id");';
        $html   .= '                data.boat_no = $("[name=\'boat_no\']").val();';
        $html   .= '                data.date_owner = $("[name=\'date_owner\']").val();';
        $html   .= '                data.name_account = $("[name=\'name_account\']").val();';
        $html   .= '                data.bsb = $("[name=\'bsb\']").val();';
        $html   .= '                data.account_no = $("[name=\'account_no\']").val();';
        $html   .= '                data.cc_card_name = $("[name=\'cc_card_name\']").val();';
        $html   .= '                data.cc_card_no = $("[name=\'cc_card_no\']").val();';
        $html   .= '                data.cc_exp_date = $("[name=\'cc_exp_date\']").val();';
        $html   .= '                data.cc_cvv = $("[name=\'cc_cvv\']").val();';
        $html   .= '                data.cc_type = $("[name=\'cc_type\']").val();';
        $html   .= '                data.nd_first_name = $("[name=\'nd_first_name\']").val();';
        $html   .= '                data.nd_surname = $("[name=\'nd_surname\']").val();';
        $html   .= '                data.nd_tel = $("[name=\'nd_tel\']").val();';
        $html   .= '                data.nd_license = $("[name=\'nd_license\']").val();';
        $html   .= '                data.status = $("[name=\'status\']").val();';
        $html   .= '                data.user = $("[name=\'user\']").val();';
        $html   .= '                data.user_id = $("[name=\'user_id\']").val();';
        $html   .= '                data.type = "add";';
        $html   .= '                $.ajax({';
        $html   .= '                    type:"POST",';
        $html   .= '                    url : "?page_id='.$attr["function_page_no"].'",';
        $html   .= '                    dataType : "text",';
        $html   .= '                    data : data,';
        $html   .= '                    success : function(result){';
        $html   .= '                        $("#status_message1").html(result);';
        $html   .= '                        removeAll();';
        $html   .= '                        makeReadonly();';
        $html   .= '                        getSurnames(document.getElementById("syndicate_list"));';
        $html   .= '                        setDefaultValues();';
        $html   .= '                    },';                  
        $html   .= '                });';
        $html   .= '                return false;   ';        
        $html   .= '            }else{';
        $html   .= '                $("#edit_button_click").val(0); ';                   
        $html   .= '            } ';          
        $html   .= '             }); ';
        $html   .= '    })(jQuery);';
           
           
        $html   .= '   function makeReadonly()';
        $html   .= '   {';
        $html   .= '       inputs = document.forms["owner_form"].getElementsByTagName("input");';
        $html   .= '       textareas = document.forms["owner_form"].getElementsByTagName("textarea");';
        $html   .= '       $("#syndicate").attr("disabled", true); ';
        $html   .= '       for (index = 0; index < inputs.length; ++index) {';
                   //alert(inputs[index].id);           
        $html   .= '           if(inputs[index].type === "radio")';
        $html   .= '           {';
        $html   .= '             inputs[index].disabled = "disabled";';
        $html   .= '           }else{';
        $html   .= '               if(inputs[index].type != "hidden")';
        $html   .= '               {';
        $html   .= '               inputs[index].readOnly = "readonly";';
        $html   .= '               }';
        $html   .= '           }';
        $html   .= '       }';
        $html   .= '       for (textindex = 0; textindex < textareas.length; ++textindex) {';
                   //alert(inputs[index].id);
        $html   .= '           textareas[textindex].readOnly = "readonly";';
        $html   .= '       }';
        $html   .= '   }';
           
        $html   .= '   function removeAll()';
        $html   .= '   {';
        $html   .= '       $("#color-error").hide(); ';
        $html   .= '       inputs = document.forms["owner_form"].getElementsByTagName("input");';
        $html   .= '       textareas = document.forms["owner_form"].getElementsByTagName("textarea");';
        $html   .= '       for (index = 0; index < inputs.length; ++index) {';
                   //alert(inputs[index].id);
        $html   .= '           if(inputs[index].type != "hidden")';
        $html   .= '           {';
                        //console.log(inputs[index].id); 
        $html   .= '           inputs[index].value = "";';
        $html   .= '           }           ';
        $html   .= '           if(inputs[index].type === "radio")';
        $html   .= '           {';
        $html   .= '               inputs[index].checked = false;';
        $html   .= '           }';
        $html   .= '       } ';  
        $html   .= '       options = "<option value=\'\'></option>";';
        $html   .= '       $("#select-first-name").html(options);';
        $html   .= '       for (textindex = 0; textindex < textareas.length; ++textindex) {';
                   //alert(inputs[index].id);
        $html   .= '           textareas[textindex].value = "";';
        $html   .= '       }';
        $html   .= '   }';
           
        $html   .= '   function setDefaultValues()';
        $html   .= '   {';
        $html   .= '       $("#edit_button_click").val(0);';
        $html   .= '       $("#add_button_click").val(0); ';
        $html   .= '   }';
           
        $html   .= '   function checkDeletion()';
        $html   .= '   {';
        $html   .= '       var status = parseInt($("#status").val());';
        $html   .= '       console.log("status - "+status);';
        $html   .= '       if(status == 0)';
        $html   .= '       {';
        $html   .= '           $("#save").click();  ';
        $html   .= '       }else{';
        $html   .= '            return true;';
        $html   .= '       } ';
        $html   .= '   }';
           
        $html   .= '   function addAction()';
        $html   .= '   {';
        $html   .= '       var editButtonClicked = parseInt ($("#edit_button_click").val());';
        $html   .= '       var deleteButtonClicked = parseInt($("#status").val());';
        $html   .= '       if(editButtonClicked)';
        $html   .= '       {';
        $html   .= '           $("#save").click();';
        $html   .= '       }else if(!deleteButtonClicked){';
        $html   .= '           $("#save").click();';
        $html   .= '       }else{';
        $html   .= '           $("#add_button_click").val(1);';
        $html   .= '           $("#id").val("");';
        $html   .= '           $("#user_id").val("");';
        $html   .= '           $("#syndicate").attr("disabled", false);';
        $html   .= '           removeAll();';
        $html   .= '           disableReadonly(); ';
        $html   .= '       }';
        $html   .= '   }';
           
        $html   .= '   function checkInputFields()';
        $html   .= '   {';
        $html   .= '        var result = true;';
        $html   .= '                for(i in validationArray)';
        $html   .= '                {';
                    //currentElementId = $('#'+validationArray[i]).attr('id');
        $html   .= '            currentElementValue = $("#"+validationArray[i]).val();';
        $html   .= '            if(currentElementValue == "")';
        $html   .= '                    {';
        $html   .= '                        var fieldName = "please enter "+validationArray[i].replace("_"," "); ';
        $html   .= '                        $("#"+validationArray[i]).val(fieldName.toUpperCase());';
        $html   .= '                        result = false;    ';                    
        $html   .= '            }else if(currentElementValue != "" && currentElementValue.indexOf("LEASE ENTER") !== -1)';
        $html   .= '            {';
        $html   .= '                result = false;';
        $html   .= '            }else if(currentElementValue != "" && validationArray[i] == "email")';
        $html   .= '            {';
        $html   .= '                var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;';
        $html   .= '                var demail = currentElementValue;';
        $html   .= '                if(!regex.test(demail)){';
        $html   .= '                  alert("You must enter a valid e-mail address");';
        $html   .= '                  return false;';
        $html   .= '                    } ';        
        $html   .= '                } ';
        $html   .= '            }   ';         
                // color validation 
        $html   .= '        color = $("[name=\'color\']:checked").val();';
        $html   .= '        if(typeof color == "undefined")';
        $html   .= '        {';
        $html   .= '            $("#color-error").show();';
        $html   .= '            result = false;';
        $html   .= '        }else{';
        $html   .= '            $("#color-error").hide();';
        $html   .= '        }';
        $html   .= '        return result; ';
        $html   .= '   }';
           
        $html   .= '   $("input").focus(function() {';
        $html   .= '        for(i in validationArray)';
        $html   .= '        {';
        $html   .= '            if($(this).attr("id") == validationArray[i])';
        $html   .= '            {';
        $html   .= '                var currentValue = $(this).val();';
        $html   .= '                if(currentValue.indexOf("LEASE ENTER") !== -1)';
        $html   .= '                {';
        $html   .= '                $("#"+validationArray[i]).val(""); ';                       
        $html   .= '                }  ';                                      
        $html   .= '            }   ';                 
        $html   .= '        } ';  
        $html   .= '    });';
           
        $html   .= '   function editAction()';
        $html   .= '   {';
        $html   .= '       var addButtonClicked = parseInt($("#add_button_click").val());';
        $html   .= '       var deleteButtonClicked = parseInt($("#status").val());';
        $html   .= '       if(addButtonClicked)';
        $html   .= '       {';
        $html   .= '           var result = checkInputFields(); ';
        $html   .= '           if(result)';
        $html   .= '           {';
        $html   .= '               $("#save").click();  ';
        $html   .= '           }            ';
        $html   .= '       }else if(!deleteButtonClicked){';
        $html   .= '           $("#save").click(); '; 
        $html   .= '       }else{';
        $html   .= '           $("#edit_button_click").val(1); ';
        $html   .= '       }   ';
        $html   .= '       disableReadonly(); ';
        $html   .= '   } ';
        $html   .= '   function disableReadonly()';
        $html   .= '   {';
        $html   .= '       checkDeletion();';
        $html   .= '       inputs = document.forms["owner_form"].getElementsByTagName("input");';
        $html   .= '       textareas = document.forms["owner_form"].getElementsByTagName("textarea");';
        $html   .= '       for (index = 0; index < inputs.length; ++index) {';
        $html   .= '           if(inputs[index].type != "hidden")';
        $html   .= '           {';
        $html   .= '           inputs[index].readOnly = false;';
        $html   .= '           }';
        $html   .= '           if(inputs[index].type === "radio")';
        $html   .= '           {';
        $html   .= '               inputs[index].disabled = false;';
        $html   .= '           }';
        $html   .= '       }';
        $html   .= '       getOwnerColors();';
        $html   .= '       for (textindex = 0; textindex < textareas.length; ++textindex) {';
                   //alert(inputs[index].id);
        $html   .= '           textareas[textindex].readOnly = false;';
        $html   .= '       }';
        $html   .= '   }';
           
        $html   .= '   function deleteRow()';
        $html   .= '   {';
        $html   .= '       var selectSurname = $("#select-surname").val();';
        $html   .= '       var addButtonClicked = parseInt($("#add_button_click").val());';
        $html   .= '       if(selectSurname != "" && !addButtonClicked)';
        $html   .= '       {';
        $html   .= '           var confirmData = confirm("Are you sure you would like to delete the customer account ?");';
        $html   .= '       if (confirmData == true)';
        $html   .= '       {';
        $html   .= '            $("#status").val(0);';
        $html   .= '       }else{';
        $html   .= '           $("#status").val(1); ';
        $html   .= '           } ';
        $html   .= '       }else{';
        $html   .= '           alert("Please select owner"); ';
        $html   .= '       }';
        $html   .= '   }';
        $html   .= '</script>';


        $html   .= '<link rel="stylesheet" type="text/css" media="screen" href="'.plugin_dir_url(__FILE__).'../../assets/addons/css/jquery-ui-1.8.2.custom.css" />';
        $html   .= '<link rel="stylesheet" type="text/css" media="screen" href="'.plugin_dir_url(__FILE__).'../../assets/addons/css/ui.jqgrid.css" />';
        $html   .= '<link rel="stylesheet" type="text/css" media="screen" href="'.plugin_dir_url(__FILE__).'../../assets/addons/css/ui.multiselect.css" />';
        $html   .= '<script src="'.plugin_dir_url(__FILE__).'../../assets/addons/js/jquery.min.js" type="text/javascript"></script> ';
        $html   .= '<script src="'.plugin_dir_url(__FILE__).'../../assets/addons/js/jquery-ui-1.8.2.custom.min.js" type="text/javascript"></script>';
        $html   .= '<script src="'.plugin_dir_url(__FILE__).'../../assets/addons/js/jquery.layout.js" type="text/javascript"></script>';
        $html   .= '<script src="'.plugin_dir_url(__FILE__).'../../assets/addons/js/grid.locale-en.js" type="text/javascript"></script>';
        $html   .= '<script src="'.plugin_dir_url(__FILE__).'../../assets/addons/js/jquery.jqGrid.min.js" type="text/javascript"></script>';
        $html   .= '<script src="'.plugin_dir_url(__FILE__).'../../assets/addons/js/jquery.tablednd.js" type="text/javascript"></script>';
        $html   .= '<script src="'.plugin_dir_url(__FILE__).'../../assets/addons/js/ui.multiselect.js" type="text/javascript"></script>';
    
        $html   .= '<link rel="stylesheet" href="'.plugin_dir_url(__FILE__).'../../assets/addons/css/validationEngine.jquery.css" type="text/css"/>';
        $html   .= '<script src="'.plugin_dir_url(__FILE__).'../../assets/addons/js/jquery.validationEngine-en.js" type="text/javascript" charset="utf-8"></script>';
        $html   .= '<script src="'.plugin_dir_url(__FILE__).'../../assets/addons/js/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>';

        $html   .= '<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />';
        $html   .= '<script src="http://code.jquery.com/jquery-1.9.1.js"></script>';
        $html   .= '<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>';

        return $html;
    }

    add_shortcode( 'owner-list', 'owner_list' );
?>